name = "FastAI"
uuid = "5d0beca9-ade8-49ae-ad0b-a3cf890e669f"
authors = ["Lorenz Ohly", "Julia Community"]
version = "0.1.0"

[deps]
Animations = "27a7e980-b3e6-11e9-2bcd-0b925532e340"
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DLPipelines = "e6530d7c-7faa-4ede-a0d6-9eff9baad396"
DataAugmentation = "88a5189c-e7ff-4f85-ac6b-e6158070f02e"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataLoaders = "2e981812-ef13-4a9c-bfa0-ab13047b12a9"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
FileTrees = "72696420-646e-6120-6e77-6f6420746567"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
FluxTraining = "7bf95e4d-ca32-48da-9824-f0dc5310474f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LearnBase = "7f8f8fb0-2700-5f03-b4bd-41f8cfc144b6"
MLDataPattern = "9920b226-0b2a-5f5f-9153-9aa70a013f8b"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MosaicViews = "e94cdb99-869f-56ef-bcf0-1ae2bcbe0389"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
ShowCases = "605ecd9f-84a6-4c9e-81e2-4798472b76a3"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
Animations = "0.4"
BSON = "0.3"
CSV = "0.8"
Colors = "0.12"
DLPipelines = "0.3"
DataAugmentation = "0.2.2"
DataDeps = "0.7"
DataFrames = "1"
DataLoaders = "0.1"
FileIO = "1.7"
FilePathsBase = "0.9"
FileTrees = "0.3"
FixedPointNumbers = "0.8"
Flux = "0.12"
FluxTraining = "0.2"
JLD2 = "0.4"
LearnBase = "0.3"
MLDataPattern = "0.5"
Makie = "0.13, 0.14"
MosaicViews = "0.2, 0.3"
Parameters = "0.12"
Reexport = "1.0"
ShowCases = "0.1"
StaticArrays = "1.1"
Tables = "1.4"
Zygote = "0.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[publish]
theme = "theme"
title = "FastAI.jl"

[targets]
test = ["Test"]
