name = "FastAI"
uuid = "5d0beca9-ade8-49ae-ad0b-a3cf890e669f"
authors = ["Peter Wolf", "Julia Community"]
version = "0.1.0"

[deps]
AbstractPlotting = "537997a7-5e4e-5d89-9595-2241ea00577e"
Animations = "27a7e980-b3e6-11e9-2bcd-0b925532e340"
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DLPipelines = "e6530d7c-7faa-4ede-a0d6-9eff9baad396"
DataAugmentation = "88a5189c-e7ff-4f85-ac6b-e6158070f02e"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
DataLoaders = "2e981812-ef13-4a9c-bfa0-ab13047b12a9"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
FileTrees = "72696420-646e-6120-6e77-6f6420746567"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
FluxTraining = "7bf95e4d-ca32-48da-9824-f0dc5310474f"
LearnBase = "7f8f8fb0-2700-5f03-b4bd-41f8cfc144b6"
MLDataPattern = "9920b226-0b2a-5f5f-9153-9aa70a013f8b"
Metalhead = "dbeba491-748d-5e0e-a39e-b530a07fa0cc"
MosaicViews = "e94cdb99-869f-56ef-bcf0-1ae2bcbe0389"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
DataDeps = "0.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[publish]
theme = "theme"
title = "FastAI.jl"

[targets]
test = ["Test"]
