name = "FastAI"
uuid = "5d0beca9-ade8-49ae-ad0b-a3cf890e669f"
authors = ["Lorenz Ohly", "Julia Community"]
version = "0.3.0"

[deps]
Animations = "27a7e980-b3e6-11e9-2bcd-0b925532e340"
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataAugmentation = "88a5189c-e7ff-4f85-ac6b-e6158070f02e"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataLoaders = "2e981812-ef13-4a9c-bfa0-ab13047b12a9"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
FluxTraining = "7bf95e4d-ca32-48da-9824-f0dc5310474f"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
ImageInTerminal = "d8c32880-2388-543b-8c61-d9f865259254"
IndirectArrays = "9b13fd28-a010-5f03-acff-a1bbcff69959"
InlineTest = "bd334432-b1e7-49c7-a2dc-dd9149e4ebd6"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LearnBase = "7f8f8fb0-2700-5f03-b4bd-41f8cfc144b6"
MLDataPattern = "9920b226-0b2a-5f5f-9153-9aa70a013f8b"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
MosaicViews = "e94cdb99-869f-56ef-bcf0-1ae2bcbe0389"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
ShowCases = "605ecd9f-84a6-4c9e-81e2-4798472b76a3"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
Animations = "0.4"
BSON = "0.3"
CSV = "0.8, 0.9, 0.10"
Colors = "0.12"
DataAugmentation = "0.2.4"
DataDeps = "0.7"
DataFrames = "1"
DataLoaders = "0.1"
FileIO = "1.7"
FilePathsBase = "0.9"
FixedPointNumbers = "0.8"
Flux = "0.12"
FluxTraining = "0.2"
Glob = "1"
ImageInTerminal = "0.4"
IndirectArrays = "0.5, 1"
InlineTest = "0.2"
JLD2 = "0.4"
LearnBase = "0.3, 0.4, 0.6"
MLDataPattern = "0.5"
MosaicViews = "0.2, 0.3"
Parameters = "0.12"
PrettyTables = "1.2"
Reexport = "1.0"
Requires = "1"
Setfield = "0.7, 0.8"
ShowCases = "0.1"
StaticArrays = "1.1"
Tables = "1.4"
UnicodePlots = "2"
Zygote = "0.6"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[publish]
theme = "theme"
title = "FastAI.jl"

[targets]
test = ["Test"]
