name = "FastTimeSeries"
uuid = "5337c758-7610-4451-a331-8357b11df7c6"
authors = ["FluxML Community"]
version = "0.1.0"

[deps]
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
FastAI = "5d0beca9-ade8-49ae-ad0b-a3cf890e669f"
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
InlineTest = "bd334432-b1e7-49c7-a2dc-dd9149e4ebd6"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
DataDeps = "0.7"
FastAI = "0.5"
FilePathsBase = "0.9"
Flux = "0.12, 0.13"
InlineTest = "0.2"
MLUtils = "0.2"
UnicodePlots = "2, 3"
julia = "1.6"