[flux-theme]
git-tree-sha1 = "6e4be8bec8da9323c18d777d7855ef79dddcf524"

    [[flux-theme.download]]
    sha256 = "b00941248ecdb643a72960bbfda19a3128591eca3d7cbcb3bfb80a6ab1c7f99e"
    url = "https://github.com/darsnack/flux-theme/releases/download/v0.2.1/flux-theme-0.2.1.tar.gz"
