[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
Publish = "f065f642-d108-4f50-8aa5-6749150a895a"
