
name: Pollen

on:
  push:
    branches: ['master']

jobs:
  publish:
    name: "Pollen Documentation (dev)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.6'
      - name: Install dependencies
        run: |
          julia --color=yes --project=. -e 'using Pkg; Pkg.instantiate()'
      - name: Build and deploy
        run: |
          cd gh-pages
          julia --color=yes --project=../docs -e "using Pkg; Pkg.instantiate()"
          julia --color=yes --project=../docs -e 'using Pkg; Pkg.develop(path=".."); Pkg.add(Pkg.PackageSpec(url="https://github.com/lorenzoh/Pollen.jl", rev="main"))'
          julia --color=yes --project=../docs ../docs/make.jl
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "(dev) Built by Publish.jl."
          git push
