name: Pollen - Render website

on:
  workflow_run:
    workflows: ['Pollen.jl build - dev', 'Pollen.jl build - PR preview', 'Pollen.jl build - Release']
    types:
      - completed
  workflow_dispatch:

# TODO: add concurrency limit
jobs:
  pollen:
    name: "Pollen - Prerender static frontend and deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: pollen
          path: data
      - uses: actions/checkout@v4
        with:
          ref: "gh-pages"
          path: pages
      - uses: actions/checkout@v4
        with:
          repository: lorenzoh/pollenjl-frontend
          path: frontend
          ref: main
      - name: Move Pollen data to static folder
        run: |
          ls
          rm -rf data/.git
          cp -r data/ frontend/static/
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: |
          cd frontend
          npm install
      - name: Build
        run: |
          cd frontend
          npm run build
      - name: Deploy changes
        run: |
          ls -lt
          rm -r frontend/build/data
          cp -r frontend/build/** pages
          cp -r data pages/
          cd pages
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -f .
          git commit -m "Deploy documentation (Pollen.jl)"
          git push
